#!/usr/bin/env python3
"""Assemble the task11 Harbor task directory (online bin packing).

Writes the generator-owned environment/Dockerfile, tests/Dockerfile,
tests/test.sh and solution/solve.sh, and stages the gitignored trees: the
agent environment (public harness subset, a config with only the published
limits, dev runner, Panda assets, rlebench.core media, instruction.md), the
verifier context (full harness, hidden seeds, score_task.py) and the solution
payload (the baseline policy). Run it (or ``make task11-assets``) after
changing tasks/task11/harness/.

A forbidden-token scan fails the build if any agent-shipped file references
the privileged packer, the scorer, calibration, the Oracle payload, the
reward weights or the hidden seeds.
"""
from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
TASK = REPO / "tasks" / "task11"
SRC = TASK / "harness"
PANDA = REPO / "assets" / "robots" / "franka_emika_panda"
CORE_FILES = ("__init__.py", "media.py")   # rlebench.core, as runtime.py records with

AGENT_FILES = ("__init__.py", "spec.py", "boxes.py", "scene.py", "sensor.py",
               "packing.py", "metrics.py", "runtime.py", "sandbox.py")
VERIFIER_FILES = AGENT_FILES + ("config.py", "golden.py", "baseline.py",
                                "scorer.py", "eval_seeds.json", "dev_runner.py")
PUBLIC_CONFIG = ("DAMAGE_FORCE_N", "DMG_TICKS", "DROP_SPEED_LIMIT",
                 "BIN_HIT_FORCE_N", "BIN_HIT_TICKS", "BIN_HIT_REARM_TICKS")
FORBIDDEN_IN_AGENT = (
    "GoldenPacker", "golden.py", "eval_seeds", "score_submission",
    "scorer.py", "dev.calibrate", "calibrate.py", "baseline.py",
    "class Packer", "_POLICY_SEED_KEY", "GOLDEN_REF_SCORE",
    "BASELINE_REF_SCORE", "GATE_CAP", "W_UTIL", "UTIL_CAP",
)

# The base image records the Debian snapshot it was built from; installing
# from that same snapshot pins every apt package (Mesa/OSMesa included).
SNAPSHOT = "20260713T000000Z"
BASE = ("FROM python:3.12-slim@sha256:"
        "57cd7c3a7a273101a6485ba99423ee568157882804b1124b4dd04266317710de")
APT = f"""RUN sed -i \\
        -e 's|http://deb.debian.org/debian-security|http://snapshot.debian.org/archive/debian-security/{SNAPSHOT}|' \\
        -e 's|http://deb.debian.org/debian|http://snapshot.debian.org/archive/debian/{SNAPSHOT}|' \\
        /etc/apt/sources.list.d/debian.sources \\
    && apt-get -o Acquire::Check-Valid-Until=false update \\
    && apt-get install -y --no-install-recommends libgl1 libosmesa6 libegl1 ffmpeg \\
    && rm -rf /var/lib/apt/lists/*"""
PIP = """RUN pip install --no-cache-dir --extra-index-url https://download.pytorch.org/whl/cpu \\
        mujoco==3.5.0 \\
        numpy==2.5.1 \\
        scipy==1.18.0 \\
        opencv-python-headless==4.13.0.92 \\
        torch==2.7.1+cpu"""

AGENT_DOCKERFILE = f"""# Agent image: pinned Python, apt snapshot and MuJoCo, headless software
# rendering, no ground truth. Generated by tasks/task11/build_assets.py; the
# pins match tests/Dockerfile.
{BASE}
{APT}
{PIP}
ENV MUJOCO_GL=osmesa
ENV RLEBENCH_ASSETS=/workspace/assets
WORKDIR /workspace
COPY assets/ /workspace/
RUN mkdir -p /logs/artifacts
"""

VERIFIER_DOCKERFILE = f"""# Verifier image (separate environment): full harness, hidden seeds and
# scorer. test.sh locks /tests before submitted code runs. Generated by
# tasks/task11/build_assets.py; the pins match environment/Dockerfile.
{BASE}
{APT}
{PIP}
ENV MUJOCO_GL=osmesa
ENV RLEBENCH_ASSETS=/tests/assets
COPY harness/ /tests/harness/
COPY rlebench/ /tests/rlebench/
COPY assets/ /tests/assets/
COPY score_task.py test.sh /tests/
RUN chmod +x /tests/test.sh && mkdir -p /logs/artifacts /logs/verifier
WORKDIR /tests
"""

TEST_SH = """#!/bin/bash
# Harbor verifier entry point (task11); only score_task.py writes rewards.
set -u
mkdir -p /logs/verifier
# Lock the verifier tree before any submitted code runs: sandboxed policies
# execute as uid 65534 and must not read the scorer or the hidden seeds.
chmod -R go-rwx /tests
PYTHONPATH=/tests python3 /tests/score_task.py
status=$?
if [ ! -f /logs/verifier/reward.json ]; then
    echo '{"reward": 0.0, "harness_error": 1}' > /logs/verifier/reward.json
    status=1
fi
exit $status
"""

SOLVE_SH = """#!/bin/bash
# Harbor Oracle for task11 (full solution, declared reward 0.6047): stages
# the public-sensor baseline packer as the deliverable. It uses only the
# agent's observations; the reward scale leaves headroom above it.
set -euo pipefail
mkdir -p /logs/artifacts
rm -rf /logs/artifacts/policy
cp -r /solution/payload/policy /logs/artifacts/policy
echo "task11 baseline policy staged."
"""

PUBLIC_CONFIG_TEMPLATE = '''"""Published limits for the packing cell.

The evaluation applies exactly these values; they are echoed in the
``cell_spec`` dict your policy receives.
"""

# A box whose contact force exceeds DAMAGE_FORCE_N for DMG_TICKS consecutive
# control ticks is crushed; a released box that makes contact moving faster
# than DROP_SPEED_LIMIT (m/s) takes an impact. Either counts as damage.
DAMAGE_FORCE_N = {DAMAGE_FORCE_N!r}
DMG_TICKS = {DMG_TICKS!r}
DROP_SPEED_LIMIT = {DROP_SPEED_LIMIT!r}

# Tool-tote contact above BIN_HIT_FORCE_N for BIN_HIT_TICKS ticks is a strike;
# the force must stay below it BIN_HIT_REARM_TICKS ticks before the next.
BIN_HIT_FORCE_N = {BIN_HIT_FORCE_N!r}
BIN_HIT_TICKS = {BIN_HIT_TICKS!r}
BIN_HIT_REARM_TICKS = {BIN_HIT_REARM_TICKS!r}
'''


def public_config() -> str:
    ns: dict = {}
    exec(compile((SRC / "config.py").read_text(), "config.py", "exec"), ns)
    return PUBLIC_CONFIG_TEMPLATE.format(**{k: ns[k] for k in PUBLIC_CONFIG})


def scan(root: Path) -> None:
    seeds = json.loads((SRC / "eval_seeds.json").read_text())
    tokens = FORBIDDEN_IN_AGENT + tuple(
        str(s) for s in [seeds["smoke"], *seeds["eval"]])
    for p in sorted(root.rglob("*")):
        if not p.is_file() or p.suffix in (".stl", ".obj", ".png", ".mjb"):
            continue
        text = p.read_text(errors="ignore")
        for token in tokens:
            if token in text:
                raise SystemExit(f"INVARIANT VIOLATION: {token!r} in "
                                 f"agent-shipped file {p}")


def _stage_common(dst: Path) -> None:
    """rlebench.core (media) and the Panda, as both images need them."""
    core = dst / "rlebench" / "core"
    core.mkdir(parents=True)
    shutil.copy(REPO / "rlebench" / "__init__.py", dst / "rlebench")
    shutil.copy(REPO / "LICENSE", dst / "rlebench" / "LICENSE")
    for name in CORE_FILES:
        shutil.copy(REPO / "rlebench" / "core" / name, core / name)
    shutil.copytree(PANDA, dst / "assets" / "franka_emika_panda")


def main() -> None:
    for sub in ("environment/assets", "tests/harness", "tests/rlebench",
                "tests/assets", "solution/payload"):
        shutil.rmtree(TASK / sub, ignore_errors=True)
    (TASK / "tests" / "score_task.py").unlink(missing_ok=True)

    env = TASK / "environment"
    env.mkdir(exist_ok=True)
    (env / "Dockerfile").write_text(AGENT_DOCKERFILE)
    assets = env / "assets"
    (assets / "harness").mkdir(parents=True)
    for name in AGENT_FILES:
        shutil.copy(SRC / name, assets / "harness" / name)
    (assets / "harness" / "config.py").write_text(public_config())
    shutil.copy(SRC / "dev_runner.py", assets / "dev_runner.py")
    shutil.copy(TASK / "instruction.md", assets / "instruction.md")
    _stage_common(assets)
    scan(assets)

    tests = TASK / "tests"
    tests.mkdir(exist_ok=True)
    (tests / "Dockerfile").write_text(VERIFIER_DOCKERFILE)
    (tests / "test.sh").write_text(TEST_SH)
    (tests / "test.sh").chmod(0o755)
    shutil.copy(SRC / "score_task.py", tests / "score_task.py")
    (tests / "harness").mkdir()
    for name in VERIFIER_FILES:
        shutil.copy(SRC / name, tests / "harness" / name)
    _stage_common(tests)

    sol = TASK / "solution"
    (sol / "payload" / "policy").mkdir(parents=True)
    shutil.copy(SRC / "baseline.py", sol / "payload" / "policy" / "policy.py")
    (sol / "solve.sh").write_text(SOLVE_SH)
    (sol / "solve.sh").chmod(0o755)
    print(f"built {TASK}")


if __name__ == "__main__":
    sys.exit(main())
