"""Emit the task01 matrix: one Harbor task per (harness level, subtask).

    python tasks/task01/build_levels.py --emit-all      # everything
    python tasks/task01/build_levels.py --emit L2       # one level
    python tasks/task01/build_levels.py --list          # the matrix
    python tasks/task01/build_levels.py --check         # disk agrees with the tables

Each `tasks/task01/L<n>/` is a Harbor DATASET directory -- one `NN-slug/` per subtask:

    harbor run -p tasks/task01/L2 -i 01-open-fridge -a <agent> ...

TWO KINDS OF OUTPUT, built at different times by different things.

    images/L<n>/    the docker build context for that level's image: Dockerfile,
                    entrypoint, and the two staged payload trees. ONE per level.
    L<n>/NN-slug/   the Harbor tasks: task.toml, the step instructions, the verifier,
                    and a docker-compose.yaml. One per subtask per level.

The subtask directories carry no Dockerfile and no payload. Harbor uses the prebuilt
`docker_image` and only consults a Dockerfile under `--force-build`
(harbor/environments/definition.py should_use_prebuilt_docker_image), so a per-subtask
build context would be one copy per subtask of a tree that is built three times.
`environment/docker-compose.yaml` IS needed per task: it carries the GPU reservation and
the read-only asset mount, and Harbor layers it over its own prebuilt template.

WHAT VARIES, and what must not. The subtasks at a level differ ONLY in
RLEBENCH_TASK and the prose that names it. The three levels differ ONLY in the harness:
same subtasks, same evaluation plan, same seeds, same reward weights, so an L1 score and
an L3 score are directly comparable. `--check` asserts both.

Everything shared is edited in `_template/`, once. Both output trees are GITIGNORED
build output, regenerated by `make task01`.
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
TEMPLATE = HERE / "_template"
IMAGES = HERE / "images"

sys.path.insert(0, str(REPO))
sys.path.insert(0, str(HERE))

from harness import config as C  # noqa: E402
from rlebench import taskgen  # noqa: E402

import build_assets  # noqa: E402

# What each level is, in one line, for task.toml's description and calibration note. The
# agent-facing account is the `steps/develop/harness_L*.md` fragment.
BLURBS = {
    "L1": "The low-level action API only: three cameras and proprioception, no object "
          "poses, no skills. The control condition.",
    "L2": "L1 plus the harness library and its manual -- frames, camera geometry, "
          "point-cloud tools and motion primitives. It runs in the agent's own process "
          "over the same metered socket, so it buys leverage and never information.",
    "L3": "L2 plus privileged simulator state -- object and fixture poses, extents, and "
          "grasp flags -- which L1 strips out. The ceiling: perception is removed from "
          "the problem and the tools are in hand.",
}

# LOWERCASE, because a Docker repository name must be. The level keeps its capital
# everywhere it is a concept (directories, RLEBENCH_LEVEL, the instructions); only the
# tag is folded, here, so the two cannot drift.
IMAGE = "rlebench-task01-{level}-agent:dev"


def image_tag(level: str) -> str:
    return IMAGE.format(level=level.lower())


def image_dir(level: str) -> Path:
    return IMAGES / level


def level_dir(level: str) -> Path:
    return HERE / level


def subtasks() -> list[tuple[int, str, str, str]]:
    """(index, RoboCasa task, slug, goal phrase) for every subtask, in ladder order."""
    return [(i, task, C.subtask_slug(i, task), goal)
            for i, (task, goal) in enumerate(C.SUBTASKS, 1)]


# -- emitting -----------------------------------------------------------------

def emit_image(level: str) -> Path:
    """The docker build context for one level's image."""
    dest = image_dir(level)
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(TEMPLATE / "image", dest)
    if level != "L1":
        shutil.copy2(REPO / "sim/perception/requirements.lock", dest)
    build_assets.stage(dest / "payload_private", build_assets.DAEMON_MODULES)
    build_assets.stage_core(dest / "payload_private")
    build_assets.stage(dest / "payload_agent", build_assets.AGENT_MODULES, level=level)

    problems = build_assets.check(dest / "payload_agent", level)
    if problems:
        raise SystemExit(f"BOUNDARY VIOLATION in images/{level}: {problems}")
    return dest


def render(text: str, level: str, task: str, slug: str, goal: str) -> str:
    return taskgen.render(text, {
        "@@LEVEL@@": level,
        "@@LEVEL_TAG@@": level.lower(),
        "@@SLUG@@": slug,
        "@@ROBOCASA_TASK@@": task,
        "@@GOAL@@": goal,
        "@@LEVEL_BLURB@@": BLURBS[level],
    })


def emit_task(level: str, index: int, task: str, slug: str, goal: str) -> Path:
    """One Harbor task: tasks/task01/L<n>/NN-slug/."""
    dest = level_dir(level) / slug
    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True)

    shutil.copytree(TEMPLATE / "environment", dest / "environment")
    shutil.copytree(TEMPLATE / "tests", dest / "tests")

    args = (level, task, slug, goal)
    (dest / "task.toml").write_text(
        render((TEMPLATE / "task.toml.in").read_text(), *args))

    # The instructions, with this level's harness section spliced in. That fragment is
    # the only agent-facing difference between the levels.
    harness = (TEMPLATE / "steps" / "develop" / f"harness_{level}.md").read_text()
    for step in ("develop", "evaluate"):
        src, out = TEMPLATE / "steps" / step, dest / "steps" / step
        shutil.copytree(src, out, ignore=shutil.ignore_patterns(
            "instruction.md.in", "harness_*.md"))
        body = render((src / "instruction.md.in").read_text(), *args)
        (out / "instruction.md").write_text(
            body.replace("@@HARNESS_SECTION@@", harness.rstrip("\n")))
    return dest


def emit_level(level: str) -> list[Path]:
    emit_image(level)
    expected = subtasks()
    keep = {slug for _, _, slug, _ in expected}
    for stale in level_dir(level).glob("[0-9][0-9]-*"):
        if stale.is_dir() and stale.name not in keep:
            shutil.rmtree(stale)
    return [emit_task(level, i, task, slug, goal)
            for i, task, slug, goal in expected]


# -- checking -----------------------------------------------------------------

def differences() -> list[str]:
    problems: list[str] = []
    expected = subtasks()

    for level in C.LEVELS:
        ctx = image_dir(level)
        if not (ctx / "Dockerfile").is_file():
            problems.append(f"images/{level} has no build context; run --emit-all")
        else:
            problems += [f"images/{level}: {p}"
                         for p in build_assets.check(ctx / "payload_agent", level)]

        present = sorted(p.name for p in level_dir(level).glob("[0-9][0-9]-*")
                         if p.is_dir())
        if present != sorted(s for _, _, s, _ in expected):
            problems.append(f"{level}/ holds {present}; expected "
                            f"{sorted(s for _, _, s, _ in expected)}")
            continue

        for _, task, slug, _ in expected:
            toml = (level_dir(level) / slug / "task.toml").read_text()
            for want in (f'"rlebench/task01-{level}-{slug}"',
                         f'"{image_tag(level)}"',
                         f'RLEBENCH_TASK = "{task}"',
                         f'RLEBENCH_LEVEL = "{level}"'):
                if want not in toml:
                    problems.append(f"{level}/{slug}/task.toml is missing {want}")
            if "@@" in toml:
                problems.append(f"{level}/{slug}/task.toml has unrendered placeholders")

            instr = (level_dir(level) / slug / "steps" / "develop"
                     / "instruction.md")
            if not instr.is_file():
                problems.append(f"{level}/{slug} has no develop instruction")
            elif "@@" in instr.read_text():
                problems.append(f"{level}/{slug} instruction has unrendered placeholders")

    problems += _levels_differ_only_in_harness()
    problems += [f"{task} has a degenerate success predicate; see config.EXCLUDED_TASKS"
                 for _, task, _, _ in expected if not C.is_scoreable(task)]
    return problems


def _levels_differ_only_in_harness() -> list[str]:
    """The comparability guarantee, asserted rather than trusted.

    Anything that differs between levels other than the harness turns a harness
    measurement into a confound. The verifier, the compose overlay and the evaluate-phase
    instruction must be identical across all three.
    """
    problems = []
    base = C.LEVELS[0]
    for level in C.LEVELS[1:]:
        for _, _, slug, _ in subtasks():
            a, b = level_dir(base) / slug, level_dir(level) / slug
            if not b.is_dir():
                continue
            for rel in ("tests/test.sh", "environment/docker-compose.yaml",
                        "steps/evaluate/instruction.md"):
                if not (a / rel).is_file() or not (b / rel).is_file():
                    continue
                if (a / rel).read_bytes() != (b / rel).read_bytes():
                    problems.append(
                        f"{level}/{slug}/{rel} differs from {base}/{slug} -- levels "
                        f"must differ only in the harness")
    return problems


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--emit", metavar="LEVEL", help="emit one level (L1, L2 or L3)")
    ap.add_argument("--emit-all", action="store_true", help="emit every level")
    ap.add_argument("--check", action="store_true", help="verify without writing")
    ap.add_argument("--list", action="store_true", help="show the matrix")
    args = ap.parse_args()

    # `--check` returns before emitting, so combining them would print a verdict about
    # the tree as it was and discard the write.
    if args.check and (args.emit or args.emit_all):
        ap.error("--emit writes, --check verifies; run them as two commands")

    if args.list:
        print(f"{len(C.LEVELS)} levels x {len(C.SUBTASKS)} subtasks = "
              f"{len(C.LEVELS) * len(C.SUBTASKS)} Harbor tasks, "
              f"{len(C.LEVELS)} images\n")
        for level in C.LEVELS:
            print(f"{level}  {image_tag(level)}\n    {BLURBS[level]}")
        print()
        for i, task, slug, goal in subtasks():
            print(f"  {slug:34s} {task:26s} {goal}")
        return 0

    if args.check:
        problems = differences()
        if problems:
            print("TASK01 MATRIX OUT OF SYNC:", file=sys.stderr)
            for p in problems:
                print(f"  {p}", file=sys.stderr)
            return 1
        print(f"matrix ok: {len(C.LEVELS)} levels x {len(C.SUBTASKS)} subtasks, "
              f"identical but for the harness")
        return 0

    if args.emit_all or args.emit:
        wanted = list(C.LEVELS) if args.emit_all else [args.emit.upper()]
        for level in wanted:
            if level not in C.LEVELS:
                raise SystemExit(f"no harness level {level!r}; --list to see them")
        for level in wanted:
            emitted = emit_level(level)
            print(f"emitted {level}: images/{level} + {len(emitted)} tasks")
        return 0

    ap.print_help()
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
